- name: Wait for MySQL container to become ready
  wait_for:
    host: "localhost"
    port: 3308
    delay: 20
    timeout: 120


- name: Copy backup_file1.sql from host to mysql container
  command: docker cp /home/ubuntu/final_assignment2/docker/backup_file1.sql mysql1:/tmp/backup_file1.sql
 # command: docker cp /home/ubuntu/final_assignment2/docker/backup.sql mysql1:/tmp/backup.sql

- name: Import backup.sql into MySQL container
#  shell: docker exec -i mysql1 bash -c 'cat /tmp/backup.sql | mysql -u root -ppassword Assignment_database'
  shell: docker exec -i mysql1 bash -c 'cat /tmp/backup_file1.sql | mysql -u edgars -pqwerty Assignment_database'
  args:
    executable: /bin/bash
